export const CREATE_DATA_REQUEST = "CREATE_DATA_REQUEST";
export const CREATE_DATA_SUCCESS = "CREATE_DATA_SUCCESS";
export const CREATE_DATA_FAIL = "CREATE_DATA_FAIL";

export const DATA_REQUEST = "DATA_REQUEST";
export const DATA_SUCCESS = "DATA_SUCCESS";
export const DATA_FAIL = "DATA_FAIL";

export const ALL_DATA_REQUEST = "ALL_DATA_REQUEST";
export const ALL_DATA_SUCCESS = "ALL_DATA_SUCCESS";
export const ALL_DATA_FAIL = "ALL_DATA_FAIL";

export const DELETE_DATA_REQUEST = "DELETE_DATA_REQUEST";
export const DELETE_DATA_SUCCESS = "DELETE_DATA_SUCCESS";
export const DELETE_DATA_FAIL = "DELETE_DATA_FAIL";
export const DELETE_DATA_RESET = "DELETE_DATA_RESET";

export const UPDATE_DATA_REQUEST = "UPDATE_DATA_REQUEST";
export const UPDATE_DATA_SUCCESS = "UPDATE_DATA_SUCCESS";
export const UPDATE_DATA_FAIL = "UPDATE_DATA_FAIL";
export const UPDATE_DATA_RESET = "UPDATE_DATA_RESET";

export const SEND_DATA_REQUEST = "SEND_DATA_REQUEST";
export const SEND_DATA_SUCCESS = "SEND_DATA_SUCCESS";
export const SEND_DATA_FAIL = "SEND_DATA_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

